// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBip8H_570v_K3oTikNgkRMHJNegPDGSs',
    appId: '1:350781593918:web:51652d0d28910b94de346f',
    messagingSenderId: '350781593918',
    projectId: 'stockcalculator-1d0f5',
    authDomain: 'stockcalculator-1d0f5.firebaseapp.com',
    storageBucket: 'stockcalculator-1d0f5.appspot.com',
    measurementId: 'G-CFWN1CRG6D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBntM40K4jzul-LeCX4Vg7bSIZTjKxDZqU',
    appId: '1:350781593918:android:1c5c6929b05ce132de346f',
    messagingSenderId: '350781593918',
    projectId: 'stockcalculator-1d0f5',
    storageBucket: 'stockcalculator-1d0f5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6AeqjmIQS1TNjJ2OiF3KKwhhKtNz4OLY',
    appId: '1:350781593918:ios:5e4725d035948a81de346f',
    messagingSenderId: '350781593918',
    projectId: 'stockcalculator-1d0f5',
    storageBucket: 'stockcalculator-1d0f5.appspot.com',
    iosBundleId: 'com.example.stcokCalculator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6AeqjmIQS1TNjJ2OiF3KKwhhKtNz4OLY',
    appId: '1:350781593918:ios:5e4725d035948a81de346f',
    messagingSenderId: '350781593918',
    projectId: 'stockcalculator-1d0f5',
    storageBucket: 'stockcalculator-1d0f5.appspot.com',
    iosBundleId: 'com.example.stcokCalculator',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBip8H_570v_K3oTikNgkRMHJNegPDGSs',
    appId: '1:350781593918:web:16a74a9e93f36b1ede346f',
    messagingSenderId: '350781593918',
    projectId: 'stockcalculator-1d0f5',
    authDomain: 'stockcalculator-1d0f5.firebaseapp.com',
    storageBucket: 'stockcalculator-1d0f5.appspot.com',
    measurementId: 'G-V2W16L8G5S',
  );
}
